import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import Header from "@/app/components/Header/index";
import "@mantine/core/styles.css";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Mazaady Task",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
				<link rel="icon" href="/mazaady.svg" />
			</head>
			<body className={inter.className}>
				<Header />
				<MantineProvider>
					<div className="container mx-auto p-2 lg:p-10">{children}</div>
				</MantineProvider>
			</body>
		</html>
	);
}
